import assert from 'node:assert/strict';
import {initialState,reduce} from '../js/state.js';
import {TOURS,tourStep} from '../js/tour-data.js';
import {createAnalyticsObserver} from '../js/analytics-model.js';
import {createMetrica,metricaAllowed} from '../js/metrica.js';
const config={counterId:'987654321',siteUrl:'https://example.org/geometry/'};
assert.equal(metricaAllowed(config,{href:'https://example.org/geometry/'}),true);
for(const href of ['http://localhost:8000/','https://example.org/other/','https://other.org/geometry/'])assert.equal(metricaAllowed(config,{href}),false);
assert.equal(metricaAllowed({...config,counterId:''},{href:config.siteUrl}),false);
let script;const win={location:{href:config.siteUrl}},doc={scripts:[],referrer:'',head:{append(s){script=s;doc.scripts.push(s);}},createElement(){return {};}};
const sdk=createMetrica(config,win,doc);assert.equal(sdk.enabled,true);assert.equal(script.async,true);
assert.equal(win.ym.a[0][1],'init');assert.equal(win.ym.a[0][2].webvisor,true);assert.equal(win.ym.a[0][2].clickmap,true);
sdk.send('hg_time',{seconds:15});assert.equal(win.ym.a.at(-1)[1],'params');
sdk.send('hg_tour_start',{tour:'torus'});assert.equal(win.ym.a.at(-1)[1],'reachGoal');
sdk.view('tour/torus/torus-cosmos','Final');assert.ok(win.ym.a.at(-1)[2].endsWith('#tour/torus/torus-cosmos'));
createMetrica(config,win,doc);assert.equal(doc.scripts.length,1,'Only one SDK request');
for(let i=0;i<1000;i++)sdk.send('hg_time',{seconds:15});assert.ok(win.ym.a.length<=160,'A blocked SDK cannot leak an unbounded event queue');
script.onerror();sdk.send('hg_tour_start');assert.equal(win.ym.a.length,0,'A failed SDK clears and stops its queue');
win.ym=()=>{throw Error('offline');};assert.doesNotThrow(()=>sdk.send('hg_test'));

let state=initialState(),time=0;const events=[],pages=[];
const observer=createAnalyticsObserver({initial:state,now:()=>time,send:(event,props)=>events.push({event,...props}),view:(...args)=>pages.push(args)});
const apply=action=>{const before=state;state=reduce(state,action);observer.update(state,before,action);};
const advance=seconds=>{time+=seconds*1000;};
advance(10);apply({type:'tour/start',id:'torus'});
assert.equal(events.find(e=>e.event==='hg_time').seconds,10);assert.equal(events.find(e=>e.event==='hg_time').section,'home');
assert.equal(events.filter(e=>e.event==='hg_tour_start').length,1);
const count=events.length;for(let i=0;i<100;i++)apply({type:'tour/tick',seconds:.01});assert.equal(events.length,count,'No per-frame events');
advance(5);apply({type:'tour/control',patch:{playing:false}});assert.equal(events.at(-1).event,'hg_tour_pause');
advance(4);observer.visibility(false);advance(100);observer.visibility(true);advance(3);observer.flush();
assert.equal(events.filter(e=>e.event==='hg_time'&&e.activity==='paused').reduce((n,e)=>n+e.seconds,0),7,'Hidden time is excluded, paused viewing is separate');
advance(2);apply({type:'knowledge/open',topic:'phi',history:false});advance(8);apply({type:'knowledge/close',resume:true,history:false});
assert.equal(events.filter(e=>e.event==='hg_time'&&e.activity==='reading').reduce((n,e)=>n+e.seconds,0),8,'Reading time is assigned to the topic, not playback');
assert.ok(events.some(e=>e.event==='hg_reading_open'&&e.topic==='phi'));
apply({type:'tour/step',index:13});assert.equal(events.filter(e=>e.event==='hg_chapter_finish').length,0,'Skipping never claims that a chapter was watched');
apply({type:'tour/tick',seconds:TOURS.torus.steps[13].seconds});
assert.equal(events.filter(e=>e.event==='hg_tour_finish').length,1);assert.equal(events.find(e=>e.event==='hg_tour_finish').all_chapters_finished,false);
for(let i=0;i<100;i++)apply({type:'tour/tick',seconds:.05});assert.equal(events.filter(e=>e.event==='hg_tour_finish').length,1,'The endless final loop completes once');
apply({type:'tour/start',id:'fruit'});
for(let i=0;i<TOURS.fruit.steps.length;i++)apply({type:'tour/tick',seconds:tourStep(state).seconds});
assert.equal(events.at(-1).event,'hg_tour_finish');assert.equal(events.at(-1).all_chapters_finished,true);
assert.equal(events.at(-1).completed_chapters,TOURS.fruit.steps.length);
advance(2);observer.suspend();const atHide=events.length;observer.suspend();assert.equal(events.length,atHide,'pagehide does not double-count');
advance(100);observer.resume(true);advance(3);observer.flush();assert.equal(events.at(-1).seconds,3);
assert.ok(pages.some(([path])=>path==='tour/torus/torus-cosmos'),'Chapter visits have stable virtual URLs');
const bad=createAnalyticsObserver({initial:state,send(){throw Error('blocked');},view(){throw Error('blocked');},now:()=>time});
assert.doesNotThrow(()=>{time+=1000;bad.flush();bad.interaction('hg_test');});
console.log('PASS: production-only SDK, bounded failure queue, semantic events, visible time, pause vs playback, skipped chapters, endless completion and harmless telemetry failure');
