import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {pathToFileURL} from 'node:url';
const three=pathToFileURL(process.argv[2]).href,url=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64'),cache=new Map();
globalThis.document={createElement:()=>({getContext:()=>({createRadialGradient:()=>({addColorStop(){}}),fillRect(){}})})};globalThis.innerWidth=1280;globalThis.innerHeight=800;
async function load(name){if(cache.has(name))return cache.get(name);let s=name==='scene'?`import * as THREE from 'three';export const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(),controls={target:new THREE.Vector3()},calls=[];camera.position.set(1,1,1).normalize().multiplyScalar(30);camera.lookAt(controls.target);export const renderer={setClearColor(){},clear(){calls.push('clear');},clearDepth(){calls.push('depth');},render(scene,camera){calls.push({scene,camera});}};`:await readFile(new URL('../js/'+name+'.js',import.meta.url),'utf8');s=s.replaceAll("'three'",JSON.stringify(three));for(const m of [...s.matchAll(/'\.\/([\w-]+)\.js'/g)])s=s.replaceAll(m[0],JSON.stringify(await load(m[1])));const result=url(s);cache.set(name,result);return result;}
const scene=await import(await load('scene')),{actions}=await import(await load('state')),{updateStarfield,renderStarfield}=await import(await load('starfield'));
updateStarfield();renderStarfield();assert.equal(scene.calls[0],'clear');assert.equal(scene.calls[2],'depth');const sky=scene.calls[1];assert.ok(sky.camera.isPerspectiveCamera);assert.equal(sky.camera.quaternion.equals(scene.camera.quaternion),true);assert.ok(Math.abs(sky.camera.position.length()-4)<1e-9);assert.equal(sky.scene.children.length,2);
for(const points of sky.scene.children){assert.equal(points.material.sizeAttenuation,true);const positions=points.geometry.attributes.position,radii=new Set();for(let i=0;i<positions.count;i++){const radius=Math.hypot(positions.getX(i),positions.getY(i),positions.getZ(i));assert.ok(radius>=29.99&&radius<=115.01);radii.add(Math.round(radius));}assert.ok(radii.size>75);}
const original=sky.camera.position.clone();scene.camera.position.multiplyScalar(100);updateStarfield();assert.ok(sky.camera.position.distanceTo(original)<1e-9,'FOV compensation must not move sky out of the sphere');
scene.camera.position.set(-30,10,40);scene.camera.lookAt(scene.controls.target);updateStarfield();assert.equal(sky.camera.quaternion.equals(scene.camera.quaternion),true,'Sky rotation must follow orbit exactly');
scene.camera.setViewOffset(1280,800,230,-22,1280,800);updateStarfield();assert.equal(sky.camera.view.offsetX,230);assert.equal(sky.camera.view.offsetY,-22);scene.camera.clearViewOffset();updateStarfield();assert.equal(sky.camera.view.enabled,false);
actions.display({starCount:8000});updateStarfield();assert.equal(sky.scene.children.reduce((sum,p)=>sum+p.geometry.drawRange.count,0),8000);
actions.display({stars:false});scene.calls.length=0;renderStarfield();assert.deepEqual(scene.calls,['clear','depth']);
console.log('PASS: genuinely spatial stars, depth attenuation, exact orbit synchronization, stable sky under FOV compensation, density and disabled rendering');
